### PR TITLE
Retyping of page0000.txt

### PR DESCRIPTION
**Pull request by sebras**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
You added a line between the two lines.  I maintain there should be just four lines.  I determined this from copying some text in between, like this: four I's between the I and the 1.
I1

**Comment by larsbrinkhoff** [comment]
Sorry, I see my version has three empty lines, not four as I intended.  So good catch, thanks!

**Comment by larsbrinkhoff** [comment]
However, here I pasted nine I's in between the I and the T.  Your version have 10 spaces.
IT

**Comment by sebras** [comment]
I measured a few characters with a ruler on my screen and then measured the distance between the characters. I did my best! :)

**Pull request merged**
